"""empty message

Revision ID: 117bd134663c
Revises: None
Create Date: 2014-05-07 10:01:29.740916

"""

# revision identifiers, used by Alembic.
revision = '117bd134663c'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('charge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Unicode(), nullable=True),
    sa.Column('citation', sa.Unicode(), nullable=True),
    sa.Column('primary_type', sa.Unicode(), nullable=True),
    sa.Column('date_created', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hash', sa.Unicode(length=64), nullable=True),
    sa.Column('gender', sa.Enum('M', 'F'), nullable=True),
    sa.Column('race', sa.Unicode(), nullable=True),
    sa.Column('date_created', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hash')
    )
    op.create_table('housing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sa.Unicode(), nullable=True),
    sa.Column('division', sa.Unicode(), nullable=True),
    sa.Column('sub_division', sa.Unicode(), nullable=True),
    sa.Column('sub_division_location', sa.Unicode(), nullable=True),
    sa.Column('date_created', sa.Date(), nullable=True),
    sa.Column('in_jail', sa.Boolean(), nullable=True),
    sa.Column('in_program', sa.Unicode(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('court_room',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('court_building',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Unicode(), nullable=True),
    sa.Column('name', sa.Unicode(), nullable=True),
    sa.Column('branch', sa.Unicode(), nullable=True),
    sa.Column('address', sa.Unicode(), nullable=True),
    sa.Column('city', sa.Unicode(), nullable=True),
    sa.Column('state', sa.Unicode(), nullable=True),
    sa.Column('zip', sa.Unicode(), nullable=True),
    sa.Column('date_created', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('court_building')
    op.drop_table('court_room')
    op.drop_table('housing')
    op.drop_table('person')
    op.drop_table('charge')
    ### end Alembic commands ###
