"""empty message

Revision ID: 1aafc5a7579d
Revises: 2ece4d2dd567
Create Date: 2014-06-06 06:31:18.769427

"""

# revision identifiers, used by Alembic.
revision = '1aafc5a7579d'
down_revision = '2ece4d2dd567'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('charge_description', 'date_created',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('charge_history', 'charge_description_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('charge_history', 'date_created',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('charge_history', 'statute_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('charge_history', 'stay_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('court_building', 'date_created',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('court_building', 'text',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('court_history', sa.Column('court_date', sa.Date(), nullable=False))
    op.alter_column('court_history', 'court_room_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('court_history', 'date_created',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('court_history', 'stay_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('court_room', 'court_building_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('court_room', 'date_created',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('court_room', 'number',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('housing', 'date_created',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('housing', 'location',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('housing_history', 'date_created',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('housing_history', 'housing_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('housing_history', 'stay_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('person', 'date_created',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('person', 'race',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('statute', 'date_created',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_column('stay', 'duration')
    op.drop_column('stay', 'last_seen')
    op.alter_column('stay', 'age_at_booking',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('stay', 'bail_amount',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('stay', 'bail_status',
               existing_type=postgresql.ENUM(u'Bond in Process', u'NO BOND', u'Set', name='bail_states'),
               nullable=False)
    op.alter_column('stay', 'booking_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('stay', 'date_created',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('stay', 'height',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('stay', 'jail_id_num',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('stay', 'person_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('stay', 'weight',
               existing_type=sa.INTEGER(),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stay', 'weight',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('stay', 'person_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('stay', 'jail_id_num',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('stay', 'height',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('stay', 'date_created',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('stay', 'booking_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('stay', 'bail_status',
               existing_type=postgresql.ENUM(u'Bond in Process', u'NO BOND', u'Set', name='bail_states'),
               nullable=True)
    op.alter_column('stay', 'bail_amount',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('stay', 'age_at_booking',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('stay', sa.Column('last_seen', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('stay', sa.Column('duration', postgresql.INTERVAL(), autoincrement=False, nullable=True))
    op.alter_column('statute', 'date_created',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('person', 'race',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('person', 'date_created',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('housing_history', 'stay_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('housing_history', 'housing_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('housing_history', 'date_created',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('housing', 'location',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('housing', 'date_created',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('court_room', 'number',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('court_room', 'date_created',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('court_room', 'court_building_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('court_history', 'stay_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('court_history', 'date_created',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('court_history', 'court_room_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('court_history', 'court_date')
    op.alter_column('court_building', 'text',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('court_building', 'date_created',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('charge_history', 'stay_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('charge_history', 'statute_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('charge_history', 'date_created',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('charge_history', 'charge_description_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('charge_description', 'date_created',
               existing_type=sa.DATE(),
               nullable=True)
    ### end Alembic commands ###
