"""empty message

Revision ID: 2ece4d2dd567
Revises: 42ca6afafeef
Create Date: 2014-05-22 21:51:19.315251

"""

# revision identifiers, used by Alembic.
revision = '2ece4d2dd567'
down_revision = '42ca6afafeef'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
