"""empty message

Revision ID: 42ca6afafeef
Revises: 46ccc3cb06c4
Create Date: 2014-05-22 21:39:03.976628

"""

# revision identifiers, used by Alembic.
revision = '42ca6afafeef'
down_revision = '46ccc3cb06c4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stay',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jail_id_num', sa.Unicode(), nullable=True),
    sa.Column('booking_date', sa.Date(), nullable=True),
    sa.Column('duration', sa.Interval(), nullable=True),
    sa.Column('bail_status', sa.Enum('Bond in Process', 'NO BOND', 'Set', name='bail_states'), nullable=True),
    sa.Column('bail_amount', sa.Integer(), nullable=True),
    sa.Column('age_at_booking', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('discharge_date', sa.Date(), nullable=True),
    sa.Column('last_seen', sa.Date(), nullable=True),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jail_id_num')
    )
    op.create_table('court_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stay_id', sa.Integer(), nullable=True),
    sa.Column('court_room_id', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['court_room_id'], ['court_room.id'], ),
    sa.ForeignKeyConstraint(['stay_id'], ['stay.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('charge_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stay_id', sa.Integer(), nullable=True),
    sa.Column('statute_id', sa.Integer(), nullable=True),
    sa.Column('charge_description_id', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['charge_description_id'], ['charge_description.id'], ),
    sa.ForeignKeyConstraint(['statute_id'], ['statute.id'], ),
    sa.ForeignKeyConstraint(['stay_id'], ['stay.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('housing_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stay_id', sa.Integer(), nullable=True),
    sa.Column('housing_id', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['housing_id'], ['housing.id'], ),
    sa.ForeignKeyConstraint(['stay_id'], ['stay.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('housing_history')
    op.drop_table('charge_history')
    op.drop_table('court_history')
    op.drop_table('stay')
    ### end Alembic commands ###
