"""empty message

Revision ID: 45e4c0464b06
Revises: c52485120f6
Create Date: 2014-05-13 21:40:39.342602

"""

# revision identifiers, used by Alembic.
revision = '45e4c0464b06'
down_revision = 'c52485120f6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('charge_description', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'charge_description', ['description'])
    op.add_column('court_room', sa.Column('court_building_id', sa.Integer(), nullable=True))
    op.alter_column('person', 'hash',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('statue', 'citation',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'statue', ['citation'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'statue')
    op.alter_column('statue', 'citation',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('person', 'hash',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.drop_column('court_room', 'court_building_id')
    op.drop_constraint(None, 'charge_description')
    op.alter_column('charge_description', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    ### end Alembic commands ###
