"""empty message

Revision ID: 46ccc3cb06c4
Revises: 45e4c0464b06
Create Date: 2014-05-15 10:37:39.673677

"""

# revision identifiers, used by Alembic.
revision = '46ccc3cb06c4'
down_revision = '45e4c0464b06'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statute',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('citation', sa.Unicode(), nullable=False),
    sa.Column('date_created', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('citation')
    )
    op.drop_table('statue')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statue',
    sa.Column('id', sa.INTEGER(), server_default="nextval('statue_id_seq'::regclass)", nullable=False),
    sa.Column('citation', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('date_created', sa.DATE(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'statue_pkey')
    )
    op.drop_table('statute')
    ### end Alembic commands ###
