"""empty message

Revision ID: c52485120f6
Revises: 117bd134663c
Create Date: 2014-05-13 19:31:44.083493

"""

# revision identifiers, used by Alembic.
revision = 'c52485120f6'
down_revision = '117bd134663c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('citation', sa.Unicode(), nullable=True),
    sa.Column('date_created', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('charge_description',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Unicode(), nullable=True),
    sa.Column('date_created', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('charge')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('charge',
    sa.Column('id', sa.INTEGER(), server_default="nextval('charge_id_seq'::regclass)", nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('citation', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('primary_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('date_created', sa.DATE(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'charge_pkey')
    )
    op.drop_table('charge_description')
    op.drop_table('statue')
    ### end Alembic commands ###
